server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: civic-track

  datasource:
    url: jdbc:h2:mem:civictrack
    driver-class-name: org.h2.Driver
    username: root
    password: lalit

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Application specific properties
app:
  jwt:
    secret: ${JWT_SECRET:mySecretKey12345678901234567890}
    expiration: 86400000 # 24 hours
  file:
    upload-dir: ./uploads
  location:
    max-radius-km: 5
    default-radius-km: 3